# Терминологический словарь для новостного переводчика
# Ключи и значения — только на английском языке
# Регистронезависимый (см. re.IGNORECASE в _postprocess_text)

TERMINOLOGY_DICT = {
    # Компании и бренды
    "Apple": "Apple",
    "Google": "Google",
    "Microsoft": "Microsoft",
    "Samsung": "Samsung",
    "Sony": "Sony",
    "Tesla": "Tesla",
    "Netflix": "Netflix",
    "Meta": "Meta",
    "Amazon": "Amazon",
    "Intel": "Intel",
    "NVIDIA": "NVIDIA",
    "AMD": "AMD",
    "Adobe": "Adobe",
    "Oracle": "Oracle",
    "IBM": "IBM",
    "Cisco": "Cisco",
    "Salesforce": "Salesforce",
    "SAP": "SAP",
    "Dell": "Dell",
    "HP": "HP",
    "Lenovo": "Lenovo",
    "Huawei": "Huawei",
    "Xiaomi": "Xiaomi",
    "TikTok": "TikTok",
    "ByteDance": "ByteDance",
    "Uber": "Uber",
    "Airbnb": "Airbnb",
    "Spotify": "Spotify",
    "Twitter": "Twitter",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "LinkedIn": "LinkedIn",
    "WhatsApp": "WhatsApp",
    "Telegram": "Telegram",
    "Discord": "Discord",
    "Slack": "Slack",
    "Zoom": "Zoom",
    "Twitch": "Twitch",
    "Disney+": "Disney+",
    "HBO Max": "HBO Max",
    "Apple TV+": "Apple TV+",
    "Amazon Prime Video": "Amazon Prime Video",
    "YouTube": "YouTube",
    "Snapchat": "Snapchat",
    "Pinterest": "Pinterest",
    "Reddit": "Reddit",
    "Quora": "Quora",
    "Medium": "Medium",
    "Wikipedia": "Wikipedia",
    "GitHub": "GitHub",
    "GitLab": "GitLab",
    "Stack Overflow": "Stack Overflow",
    "Mozilla": "Mozilla",
    "Firefox": "Firefox",
    "Chrome": "Chrome",
    "Safari": "Safari",
    "Edge": "Edge",
    "Opera": "Opera",
    "Brave": "Brave",
    "Tor Browser": "Tor Browser",

    # Криптовалюты
    "Bitcoin": "Bitcoin",
    "Ethereum": "Ethereum",
    "Dogecoin": "Dogecoin",
    "Ripple": "Ripple",
    "Litecoin": "Litecoin",
    "Solana": "Solana",
    "Cardano": "Cardano",
    "Polkadot": "Polkadot",
    "Chainlink": "Chainlink",
    "Uniswap": "Uniswap",

    # ИИ и технологии
    "OpenAI": "OpenAI",
    "ChatGPT": "ChatGPT",
    "GPT-3": "GPT-3",
    "GPT-4": "GPT-4",
    "Bard": "Bard",
    "Claude": "Claude",
    "Perplexity": "Perplexity",
    "Midjourney": "Midjourney",
    "DALL-E": "DALL-E",
    "Stable Diffusion": "Stable Diffusion",
    "Artificial Intelligence": "Artificial Intelligence",
    "Machine Learning": "Machine Learning",
    "Deep Learning": "Deep Learning",
    "Neural Network": "Neural Network",
    "Blockchain": "Blockchain",
    "Cryptocurrency": "Cryptocurrency",
    "Big Data": "Big Data",
    "Cloud Computing": "Cloud Computing",
    "Internet of Things": "Internet of Things",
    "Augmented Reality": "Augmented Reality",
    "Virtual Reality": "Virtual Reality",
    "Quantum Computing": "Quantum Computing"
}